name: Run PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, mysqli, xdebug
        coverage: xdebug

    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo service mysql start
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS tests;"

    - name: Install dependencies
      run: |
        composer install

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h 127.0.0.1 --silent; do
          echo "Waiting for MySQL..."
          sleep 1
        done

    - name: Run PHPUnit tests
      run: |
        ./vendor/bin/phpunit --coverage-text
