name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tests
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'
          extensions: mbstring, intl, pdo_mysql, mysqli, xdebug
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Debug PHPUnit version
        run: ./vendor/bin/phpunit --version

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -u root --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "MySQL not ready yet, waiting..."
            sleep 2
          done

      - name: Configure database connection
        run: |
          echo "Setting up database connection"
          echo "database.default.hostname = 127.0.0.1" >> .env
          echo "database.default.username = root" >> .env
          echo "database.default.password = " >> .env
          echo "database.default.database = tests" >> .env
          echo "database.default.DBDriver = MySQLi" >> .env
          echo "database.default.port = 3306" >> .env
          echo "database.tests.hostname = 127.0.0.1" >> .env
          echo "database.tests.username = root" >> .env
          echo "database.tests.password = " >> .env
          echo "database.tests.database = tests" >> .env
          echo "database.tests.DBDriver = MySQLi" >> .env
          echo "database.tests.port = 3306" >> .env

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text tests/Models/UserModelTest.php
