name: PHPUnit Tests UserModel + BonLivraisonModel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: tests
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'
          extensions: mbstring, intl, pdo_mysql, mysqli, xdebug
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v3


      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
      
      - name: Check PHPUnit version
        run: vendor/bin/phpunit --version
      
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -u root --silent; then
              break
            fi
            sleep 2
          done
      
      - name: Prepare database schema
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root tests <<EOF
          CREATE TABLE IF NOT EXISTS users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL
          );
          CREATE TABLE IF NOT EXISTS bonlivraison (
            id INT AUTO_INCREMENT PRIMARY KEY,
            status VARCHAR(50) NOT NULL,
            delivery_date DATE NOT NULL
          );
          CREATE TABLE IF NOT EXISTS lignebonlivraison (
            id INT AUTO_INCREMENT PRIMARY KEY,
            id_bonlivraison INT NOT NULL,
            designation VARCHAR(255) NOT NULL,
            quantity INT NOT NULL,
            FOREIGN KEY (id_bonlivraison) REFERENCES bonlivraison(id)
          );
          EOF
      
      - name: Configure environment
        run: |
          cat <<EOF >> .env
          database.default.hostname = 127.0.0.1
          database.default.username = root
          database.default.password =
          database.default.database = tests
          database.default.DBDriver = MySQLi
          database.default.port = 3306
          EOF
      
      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --coverage-text tests/Models/UserModelTest.php
          ./vendor/bin/phpunit --coverage-text tests/Models/BonLivraisonModelTest.php 
      