name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Autorise une connexion sans mot de passe
        ports:
          - "3306:3306"

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    # Install dependencies
    - name: Install dependencies
      run: |
        composer install --no-interaction

    # Configure environment variables for DB
    - name: Set up DB environment variables
      run: |
        echo "DB_DEFAULT_HOSTNAME=127.0.0.1" >> $GITHUB_ENV
        echo "DB_DEFAULT_DATABASE=tests" >> $GITHUB_ENV
        echo "DB_DEFAULT_USERNAME=root" >> $GITHUB_ENV
        echo "DB_DEFAULT_PASSWORD=" >> $GITHUB_ENV
        echo "DB_DEFAULT_DBDriver=MySQLi" >> $GITHUB_ENV

    # Wait for MySQL service to be ready
    - name: Test MySQL connection
      run: |
        mysql -h 127.0.0.1 -u root -e "SHOW DATABASES;"
  

    # Run PHPUnit tests
    - name: Run PHPUnit tests
      run: php vendor/bin/phpunit --configuration phpunit.xml.dist
