name: PHPUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.2'  # Remplacez avec la version PHP appropriée

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libxml2-dev
          composer install

      - name: Run PHPUnit tests
        run: |
          vendor/bin/phpunit --configuration phpunit.xml.dist
