name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tests
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-start-period=30s
          --health-timeout=5s
          --health-retries=3

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    # Install dependencies
    - name: Install dependencies
      run: |
        composer install --no-interaction

    # Configure environment variables for DB
    - name: Set up DB environment variables
      run: |
        echo "DB_DEFAULT_HOSTNAME=127.0.0.1" >> $GITHUB_ENV
        echo "DB_DEFAULT_DATABASE=tests" >> $GITHUB_ENV
        echo "DB_DEFAULT_USERNAME=root" >> $GITHUB_ENV
        echo "DB_DEFAULT_PASSWORD=root" >> $GITHUB_ENV
        echo "DB_DEFAULT_DBDriver=MySQLi" >> $GITHUB_ENV

    # Wait for MySQL service to be ready
    - name: Wait for MySQL
      run: |
        until mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"; do
          echo "Waiting for database..."
          sleep 5
        done

    # Run PHPUnit tests
    - name: Run PHPUnit tests
      run: php vendor/bin/phpunit --configuration phpunit.xml.dist
